<<<<<<< HEAD
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install project packages
        run: python -m pip install --upgrade pip && python -m pip install -r requirement.txt

      - name: Check code style formatting
        run: python -m black --check .

      - name: Run code linter
        run: python -m pylint web_app

      - name: Run type checks
        run: python -m mypy web_app

      - name: Run unit tests
        run: python -m pytest
